shelljs/shx

- package.json
- src/cli.js
- src/printCmdRet.js
- src/shx.js
- test/cli.js
This PR finishes ava setup and adds a single test as an example.  More tests and utlis will be created in separate PRs.
> Setup tests

- src/shx.js
Running `cli.js` from current `master` branch:
```
shx|master ⇒ npm run build && ./lib/cli.js pwd
> shx@0.0.1 prebuild /Users/scott/Documents/sites/shx
> rimraf lib
> shx@0.0.1 build /Users/scott/Documents/sites/shx
> babel src -d lib
src/cli.js -> lib/cli.js
src/printCmdRet.js -> lib/printCmdRet.js
src/shx.js -> lib/shx.js
/Users/scott/Documents/sites/shx/lib/shx.js:58
if (fnName !== 'echo') (0, _printCmdRet2.default)(ret);
^
TypeError: (0 , _printCmdRet2.default) is not a function
at shx (/Users/scott/Documents/sites/shx/lib/shx.js:58:52)
at Object.<anonymous> (/Users/scott/Documents/sites/shx/lib/cli.js:8:27)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at …
```
> fix: fixed import statement

- .eslintrc
- src/printCmdRet.js
- src/shx.js
This fixes the fiasco raised by shelljs/shelljs#420. This should be compatible with the current state of ShellJS and should *also* work with any reasonable response to that issue in ShellJS.
Stuff that used to be broken:
- Printing any command would look like junk (there was a simple logic error). It would print the internal representation of ShellStrings, not the string value.
Once the logic error was fixed, there were all sorts of other bugs:
- error messages would be printed twice
- `shx cat package.json` added an extra newline (also with `sort`, `head`, `tail`, and probably many others)
- `test -f package.json` would output `true` to the console (it should be silent, just return a "true" exit code)
- `test -d package.json` would output nothing, but would exit with status `0` (now it …
> fix: trailing newlines are now consistent

- package.json
Once we publish to `npm`, the current package would perform a build on the user's machine during an `npm i`.  This PR will ensure the build assets are published to NPM beforehand.  This way, there is no build necessary locally.  The built `lib` folder will exist, but only on NPM, still not in our codebase.
> Build on prepublish

- .eslintrc
- package.json
- test/.eslintrc
- test/mocha.opts
- test/setup.js
- test/specs/cli.js
> Switch to mocha

- package.json
shelljs v0.7 just got released, so this should make things more stable for shx.
> chore: update shelljs dependency

- .gitignore
- .travis.yml
- package.json
closes #19 
This PR adds `test:coverage` npm script to run test coverage, as well as including setup to codecov coverage (https://codecov.io/) after travis CI completes. Repo owner need to enable repository watching in codecov to collect coverage data.
Actual results can be looked at https://codecov.io/gh/kwonoj/shx/src/880e389d000d60080a65cc9dee7fbed69bc72b8d/src/shx.js , ran against forked repo.
> chore(package.json): add test coverage script

- package.json
As raised in #35, this PR shows coverage after `npm test`.
> Show test coverage on every run

- .travis.yml
- appveyor.yml
Does what it says. I'm trying to bump appveyor up to v6 again, but if it doesn't work, I'll just take out that change.
> chore(CI): update to node v6

- CONTRIBUTING.md
- package.json
- scripts/release.sh
This PR will conclude any open issues.  Folks are ready to use it (#29 #40) and I believe we ready to let them start.
I've added release scripts that are battle tested and a README snippet on how to use them.  Once this PR is ready, we'll just have to run this to release the first `v0.1.0` to NPM:
```shell
npm run release:minor
```
Closes #40.
> Initial release

- package.json
- src/cli.js
- src/shx.js
- test/specs/cli.js
Removes babel-polyfill as a dependency (as brought up [here](https://github.com/shelljs/shx/issues/43#issuecomment-216674099)) and (as far as I can tell) works on node v4+.
If I missed any methods that should be changed, please let me know.
> refactor: remove babel-polyfill dep

- README.md
Adds coverage badge.
Also moves to modern and consistent flat style with shields.io.  We avoided this last time due to the lack of distinction between travis and appveyor badges.  I've changed the `label` on those build badges to be `[unix: passing]` and `[windows: passing]` to show the difference.
> Add codecov badge and switch to flat styles

- scripts/release.sh
We've run into an edge case at TA with the release script.  If you are an owner on a package but also not a collaborator with write access, the publish script wouldn't see your permissions.
This PR just adds an `is_owner` check, allowing non-collaborator owners to publish.
> Allow npm owner releases

- CHANGELOG.md
- package.json
- scripts/changelog.sh
Resolves #18.
The changelog and changelog commit in this PR were generated using the script.  See commit:
```
docs(changelog): updated by levithomason [ci skip]
```
```shell
› npm run changelog 
...generating changelog (be patient)
...committing updated changelog
Done.  You can now 'git push' the updated changelog.
```
When the the changelog is already up to date and the script is run:
```shell
› npm run changelog
...generating changelog (be patient)
CHANGELOG.md already up-to-date.
```
Later, this script can be integrated into the CI process.  The repo/branch/user can be inferred from CI env vars at that time as well.   This just gets it started.
> chore(changelog): create and add script

- README.md
- package.json
- src/shx.js
- test/specs/cli.js
Fixes #61 
This works with anything supported by `shell.config`. So if you want to change `shell.config.foo` to the value `true` for the `ls` command, you can specify `shx --foo ls`.
`shx --silent ls` won't silence all output, only error output, since that's currently how `config.silent` works. If we want `shx` to work differently, I can modify this to do a special check for the `--silent` flag and also silence stdout.
> feat: --silent will silence error output

- package.json
Updates to the latest version, which has a namespaced CLI. Doesn't change anything else.
> chore: update shelljs-release

- README.md
Fixed #59.  This PR lists the unsupported commands in the README.  I have not added the workarounds.  Hoping to get some help from @nfischer on that.
> docs: unsupported commands

- README.md
This just adds the npm version badge for shx:
[![npm (scoped)](https://img.shields.io/npm/v/shx.svg?style=flat-square)](https://www.npmjs.com/package/shx)
> docs: add npm README badge

- README.md
This is a follow up to #69. This turns it into a table, with the workaround on the right.
As I was writing it, I realized that we do have workarounds for the `set()` command, so I documented the options available there, and linked everything back to shelljs's documentation.
> docs: add workarounds for unsupported commands

- .travis.yml
- package.json
I was setting up my own project for codecov and I noticed that the recommended steps on their site differed from what we have here. And it cuts out an extra dependency, so I figured I'd make a PR.
[Here's the project](https://github.com/nfischer/shelljs-exec-proxy) I set up, and it seems to work properly.
> chore: remove unnecessary dependency

- src/shx.js
- test/specs/cli.js
Fixes #74 
This lets `shx sed` work properly:
```bash
$ shx sed -i 's/foo/bar/' file.txt
$ shx sed 's/first/second/g' file2.txt
```
If you can think of a way to make things less verbose in the code, let me know.
> fix: allow sed to use a unix syntax

- src/shx.js
- test/specs/cli.js
This should make `shx sed` work a little bit better. Also, this should make the code a bit more readable. If you have any readability suggestions, chime in and I'll implement those.
> fix: sed works with slashes in regex

- .gitignore
- package.json
- src/config.js
- src/help.js
- src/shx.js
- test/specs/cli.js
This adds support for ShellJS plugins. This can be used by creating a config file for shx, `.shxrc.json` in the root of your package (assuming that you'll be running `shx` via npm scripts). The file should be formatted as such:
```json
{
"plugins": [
"shelljs-plugin-foo"
]
}
```
This will load in the `shelljs-plugin-foo` plugin. This plugin must be required by the user as a dependency (or dev dependency) in the project, otherwise shx will fail for every command.
Once we officially support ShellJS plugins, we should update the README for shx to show plugin usage instructions.
> feat: support for ShellJS plugins

- README.md
Adds a gitter badge for # of downloads per month. We could switch this to number of total downloads if you think that would be more interesting.
> chore: add npm downloads per month

- .travis.yml
- package.json
- src/shx.js
I don't think this is too much of a maintenance burden, and it lets us take advantage of shx from within shelljs, which I think is a big win.
If I missed anything, let me know.
This blocks shelljs/shelljs#525
> chore: add support for v0.11+

- src/cli.js
- src/shx.js
- test/mocks.js
- test/specs/cli.js
Read all of stdin and pass it to the underlying ShellJS command. This is also
adds support for mocking stdin during tests, and refactors the mock utilities.
Fixes #80
If @levithomason doesn't have time to review, I can just merge this in a day or two (assuming everything passes)
> feat: pass stdin along to ShellJS commands

- src/cli.js
- src/config.js
- test/specs/cli.js
Don't deadlock waiting for stdin during situations when stdin is not expected.
Fixes #95
> fix: only wait for stdin when appropriate

- .travis.yml
iojs tends to be flaky on Travis for some reason. Let's ignore failures on these
builds for now.
Fixes #99
> chore: allow Travis failures on iojs

- src/shx.js
- test/specs/cli.js
Now works with using the empty string as a replacement string
Some details on allowed regexes (in unix `sed`):
* `s/foo/bar/`: the string must end in a slash (or with `/g` or something similar)
* `s/foo//`: the replacement string is allowed to be empty
* `s/a/b/`: the regex must be at least one character long
* `s/foo/bar\./g`: the `\.` is treated as a literal dot
* `s/foo/bar./g`: the `.` is also treated as a literal dot, when in the replacement string
* `s/foo./bar/g`: the `.` is **not** treated literally when in the regex string
* `s/foo\//bar\//g`: the `\/` is treated as a literal `/` in either string
Fixes #109
> fix: better regex support for sed

- README.md
As discussed in https://github.com/shelljs/shx/issues/121.
> Add workaround for pushd and popd to README

- src/cli.js
Issue #85
Fixes #116 
This is a follow-up to the initial PR. This favors `process.exitCode` over
`process.exit()` to guarantee that we don't terminate while streams are still
open.
This should have no effect on behavior, this is just a cleaner fix over the
previous hack.
Test: manually verify with `shx cat input.txt | wc` (`input.txt` is Lorem ipsum)
> fix: use process.exitCode to wait for streams

- .travis.yml
- appveyor.yml
This adds Node v10 to Appveyor and Travis CI.
> chore(CI): add node v10 to CI

- src/config.js
- src/shx.js
- test/specs/cli.js
These issues are pointed out by the latest version of nyc. Fixing these
issues brings us to 100% coverage (as of nyc@v12.0.2).
Fixes include:
* ignore coverage for a condition we don't hit during testing
* branch coverage for when we read stdin for commands with non-boolean
options (e.g., head, tail)
* branch coverage for plugin-behavior with config files lacking a
plugin attribute
Issue #134
> test(coverage): fix coverage issues

- src/shx.js
- test/specs/cli.js
This PR does:
1. Refactors sed-specific pattern-conversion logic. This logic converts
a unix-style pattern (e.g., "s/foo/bar/") into the separate
parameters expected by shell.sed() (e.g., new RegExp('foo'), 'bar').
This builds the RegExp more carefully to avoid the issue with
escaped slashes (as reported in #136).
2. Explicitly checks for empty patterns and throws an error
(previously, these would just silently fail conversion).
3. Adds tests for the previous two cases.
4. Refactors the sed tests to be more maintainable by saving file
contents in test variables. No change in the logic of
already-existing tests.
Fixes #136
Test: 'works with backslashes and forward slashes in pattern'
Test: 'does not work with empty regex strings'
> fix(sed): better support for converting sed patterns

- package-lock.json
- package.json
- test/mocha.opts
This fixes 2 issues, both of which are vaguely related to babel
transpiling during tests:
* The new mocha version uses the `--require` flag instead of
`--compilers`.
* nyc 12.0.0 causes mysterious "Transformation errors" with transpiling
during tests.
This PR addresses the first issue by switching the flag as required.
This PR addresses the second issue by downgrading nyc, as v11 is the
last release which supports node v4.
Fixes #144
> chore: fix issues with nyc and mocha

- src/config.js
- src/help.js
- test/specs/cli.js
This adds an 'shx-options' section the help output, covering options
such as --fatal, --silent, etc.
This also reformats existing help text slightly.
Fixes #101
> feat: help command provides info on options

- src/plugin-true-false.js
- src/shx.js
- test/specs/cli.js
This implements true and false as a single plugin, and adds this plugin
by default to shx.
Fixes #105
Test: automated tests
Test: manual (works as expected)
> feat: add true and false as default commands

- package-lock.json
- package.json
This updates `watch`. This package transitively depends on an old
version of `merge` with a security vulnerability.
> chore: update dev dependency

- package-lock.json
- package.json
- src/shx.js
No change to logic, this just removes a dependency because we target
node >= v4 (which already supports Object.assign).
Fixes #146
> chore: remove es6-object-assign dependency

- .travis.yml
See also: shelljs/shelljs#910
This switches Travis to use the node_js language. We originally used the
C++ language because OS X didn't properly support the node_js language
(so we had to do all setup manually). This is no longer the case.
> chore(ci): switch to node language for travis

- .travis.yml
- README.md
- package.json
- scripts/.eslintrc.json
- scripts/check-node-support.js
No change to node support, this just adds a script.
This adds a script to check that we correctly configure all supported
node versions, since we need to update quite a few spots (README.md,
package.json, travis, appveyor).
Issue shelljs/shelljs#873
Test: manual
> chore: script to bump supported node versions

- README.md
No change to logic, only docs.
This documents the special sed syntax (ex. `shx sed s/foo/bar/g
filename.txt`). With that, this mentions that `/` is a special
character, so the user must escape that if it's present in either the
regex or replacement string.
This also documents how Windows handles single quotes differently, so
it's desirable to avoid single quotes in package.json scripts. This part
isn't specific to sed, but since it's popular to quote sed expressions,
I'm adding this to the docs at the same time.
Fixes #165
Fixes #169
> docs(sed): document sed syntax, quoting, and escaping slash

- package.json
https://github.com/shelljs/shelljs/pull/973 updated shelljs to prevent Node 14 from flooding the user with hundreds of lines that look like:
```
(node:117) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:117) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:117) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:117) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:117) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:117) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:117) Warning: Accessing …
```
> Update shelljs to avoid circular dependency warnings on Node 14

- src/config.js
- src/help.js
- src/shx.js
- test/specs/cli.js
No change to logic. This just renames "blacklist" to "blocklist" to use
more inclusive language.
Test: npm run test
Test: ./lib/cli.js exec (this is blocked, as expected)
Test: ./lib/cli.js help (does not mention blocked commands)
> refactor: rename "blacklist" -> "blocklist"

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. This adds node v15 and v16 to the CI testing.
> chore(ci): run tests up to node v16

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. This updates GitHub actions to test up through node
v18.
> chore: update CI to include v18

- package.json
- src/shx.js
- test/specs/cli.js
I can't reproduce these warnings locally, but these appear to be failing on CI. This is a speculative fix.
> fix(lint): fixes import order lint warnings

- README.md
This adds an "important" callout to emphasize that double quotes are necessary and single quotes won't work.
Fixes #213
> doc: highlight globs and emphasize double quotes

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. This updates GitHub actions CI to test on node v19 and v20.
> chore: update CI to test against node v20

- .github/workflows/main.yml
GitHub is removing all versions < v16 from GitHub actions. I'm trying to keep Node coverage for as long as possible.
Issue shelljs/shelljs#1140
> chore: keep node < 16 around longer

- .github/workflows/main.yml
This PR bumps two GitHub workflow actions to their latest versions, as requested [here](https://github.com/shelljs/shelljs/pull/1136).
> Bump GitHub workflow action to latest version

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. GitHub Actions recently dropped some NodeJS
configurations from their service. This excludes those configs from our
CI.
This also adds Node versions up through v22.
Test: npm run check-node-support
> chore: remove unsupported node configs from CI

- package.json
- scripts/check-node-support.js
This updates js-yaml to 4.1.0 and swaps out `yaml.safeLoad()` for `yaml.load()` because the `safe*` functions are deprecated starting in 4.0.0 (the "regular" functions are considered safe).
> chore(dependencies): update js-yaml

- .github/workflows/main.yml
- README.md
- package.json
- scripts/check-node-support.js
- src/shx.js
- test/specs/cli.js
This updates the ShellJS peer dependency to the latest release. This also drops support for all node versions prior to v18 to match ShellJS's version range.
This includes some changes due to the latest shelljs version:
* `shx sed -i` will now run silently. This is compatible with unix behavior. See shelljs/shelljs#959
* `shx --version` no longer prints the ShellJS version. This is a consequence of the switch to an explicit "exports" list in shelljs (see shelljs/shelljs#1195 and shelljs/shelljs#1135).
Test: npm test
> chore: update shelljs and drop old node support

- .github/workflows/main.yml
- README.md
- scripts/check-node-support.js
No change to logic. This drops support for non-LTS versions and it also drops everything before node v18 (this will be required anyway for shelljs v0.9).
> chore: drop non-LTS node versions

- .github/workflows/main.yml
- package.json
No change to logic. This drops support for some of the package commands that I never run. We can trim out a few dependencies this way.
This also adds `npm run build` as a step in CI since I realized this probably wasn't actually ever tested on CI.
> chore: drop some dependencies and simplify

- .gitignore
- package-lock.json
- package.json
- src/shx.js
- test/specs/cli.js
This is a small fix for the `--version` flag. This adds back ShellJS version number, which was re-exposed in PR shelljs/shelljs#1200. This reverts one of the workarounds added in PR #228.
This also commits package-lock.json to the repo.
> fix: add back ShellJS version in --version

- package-lock.json
- package.json
No change to logic. This updates the ShellJS peer dependency to the latest release.
This also bumps shelljs-plugin-open since this is compatible with the latest shelljs release.
Test: npm test
> chore: update shelljs

- src/config.js
- test/specs/cli.js
This adds support for https://github.com/shelljs/shelljs/pull/1206. This requires special parsing logic on the shx side.
Test: npm test
Test: ./lib/cli.js grep -A 1 'foo' ~/foobartest.txt
Test: cat ~/foobartest.txt | ./lib/cli.js grep -A 1 'foo'
> feat: support option parsing for grep -C flag
