src/cli.js
=> fix: blacklist certain commands

src/shx.js
=> fix(echo): fix #5

package.json
=> Use ShellJS GitHub dependency

package.json
=> Add missing rimraf devDependency

README.md
Similar to shelljs/shelljs#423
=> chore: add "Team" section to README

.travis.yml, README.md, appveyor.yml
=> chore(CI): add CI badges to README.md

.eslintignore
Fixes #36
@levithomason: Ready for review
=> chore(lint): don't lint coverage results

package.json
=> fix(deps): add babel-polyfill as a runtime dep

test/mocks.js, test/specs/cli.js
Played around with the test framework a bit more, and got some better test coverage. Let me know if anything should be revised.
Not sure if we can get much more coverage without modifying the src, since I think we have some branches that were only reachable via old versions of ShellJS.
=> test: improve test coverage

test/specs/cli.js
This adds unit tests for these commands, giving us a little more assurance that they work correctly and won't break in the future. This skips `chmod` tests since ShellJS skips them for Windows.
=> test: add unit tests for grep and chmod

.travis.yml, package.json, src/shx.js
=> refactor: use fs.existsSync

.travis.yml, appveyor.yml
=> Add node v7 to CI

test/mocks.js
=> chore: fix spelling error

.lgtm, MAINTAINERS
=> Remove lgtm.co related files

README.md
This used to be under Ari's account, but since he's no longer involved and his appveyor webhook doesn't seem to be working, this is moved over to my account.
Fixes #97
=> chore: switch appveyor to shelljs account

.travis.yml, appveyor.yml
=> Add node 8 to CI

.travis.yml, appveyor.yml, package.json
This bumps shelljs to v0.8.1.
Fixes #125
=> feat: bump shelljs to expose new features

.travis.yml, appveyor.yml
This changes codecov configuration to stay consistent with shelljs. This
adds codecov for appveyor (we weren't already running it?).
=> chore(ci): fix codecov

package.json
See [this](https://github.com/substack/minimist#security) for more info.
=> Upgrade minimist to avoid security vulnerability

.gitignore, .npmrc, package.json
No change to logic. This updates dependencies, which includes
shelljs/shelljs#1058.
=> chore: update dependencies

CONTRIBUTING.md, README.md
No change to logic. This updates the main branch name in the README.
=> chore: rename master -> main

package.json
Addresses https://github.com/advisories/GHSA-xvch-5gv4-984h
=> Update minimist for CVE-2021-44906

.github/workflows/main.yml
No change to logic. This adds a codecov token to the project.
=> chore: add codecov token
